name: helm-package-and-deploy

on:
  push:
    branches:
      - dev

jobs:
  package-and-deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    container:
      image: hotbird.docker.nexus.macslabs.de/docker/ci-helm-image:1d2426f
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history for all branches and tags      